version: '3.7'

services:
  v2fly-relay:
    restart: always
    image: whatwewant/v2fly-relay:${SERVICE_V2FLY_RELAY_VERSION}
    environment:
      UPSTREAM: ${SERVICE_V2FLY_RELAY_UPSTREAM}
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
      - ${SERVICE_LOGS}:/var/log/v2ray

networks:
  default:
    external: true
    name: compose-ingress
